# Site settings
title: Web3 Crypto Streaming Service
email: contact@web3streaming.example
description: A decentralized content streaming platform built on blockchain technology
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://web3streaming.example.com"
twitter_username: web3streaming
github_username: web3streaming
author: Web3 Crypto Team

# Build settings
markdown: kramdown
permalink: /blog/:year/:month/:day/:title/

# Blog settings
show_excerpts: true
paginate: 9
paginate_path: "/blog/page:num/"

# Collections
collections:
  faqs:
    output: true
    permalink: /faq/:name/
  use_cases:
    output: true
    permalink: /use-cases/:name/
  authors:
    output: true

# Default front matter
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
      author: "Web3 Streaming Team"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag

# Social media
social:
  name: Web3 Crypto Streaming
  links:
    - https://twitter.com/web3streaming
    - https://github.com/username/web3-crypto-streaming-service

# Google Analytics (replace with your tracking ID in production)
google_analytics: UA-XXXXXXXXX-X

# Exclude from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore
