# Site settings
title: Web3 Crypto Streaming Service
description: A decentralized platform for content streaming built on blockchain technology
baseurl: "/gh-pages"
url: "https://idl3o.github.io"
github_username: idl3o

# Build settings
markdown: kramdown
exclude:
  - node_modules
  - "*.gemspec"
  - "*.gem"
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - script/
  - LICENSE.txt
  - lib/
  - bin/
  - README.md
  - Rakefile
  - docs/tests/

# Exclude files with problematic Liquid syntax
include:
  - _pages

# Prevent Jekyll from processing specific files with Liquid syntax issues
defaults:
  - scope:
      path: "node_modules/balanced-match/README.md"
    values:
      sitemap: false
      render_with_liquid: false

# Theme and plugins
theme: minima
plugins:
  - jekyll-seo-tag

# Custom variables
version: 0.9.0-beta.1
